### ISSUE TITLE
Error Occured in Flow

### ISSUE THREAD

**Issue by MattHoldgate** [jongpie/CustomMetadataSaver#11]
Hi

When creating metadata records I am receiving an error "The number of results does not match the number of interviews that were executed in a single bulk execution request." I think it is possibly when the flow is getting fired twice. Is there something I need to do to resolve this?

Thanks
Matt
<img width="1157" alt="Screenshot 2021-07-14 at 11 28 09" src="https://user-images.githubusercontent.com/83656370/125607308-e287eff8-47e3-4b0d-807a-557ff3f38798.png">

**Comment by jongpie** [comment]
Hi @MattHoldgate - thanks for reporting this! I've made a small pull request to solve this issue, PR #12. I'll merge it later today!

**Comment by jongpie** [comment]
@MattHoldgate, I've merged that bugfix to the `main` branch - if you redeploy the repo to your org, it should now work for you. Let me know if you run into any other issues!

**Comment by MattHoldgate** [comment]
Thanks, @jongpie that's brilliant. Works first time!
