### ISSUE TITLE
Installation failing in sandbox 

### ISSUE THREAD

**Issue by ShijiMathew** [jongpie/CustomMetadataSaver#22]
I am trying to install this package in our sandbox org and getting compile failure issue. Attached screenshot of mail

**Comment by jongpie** [comment]
Hi @ShijiMathew - that looks like an issue with an existing class in your org called `getSetNumbersListener`. By default, when installing packages in your org, Salesforce compiles all of the Apex in your org, and this existing issue in your org is blocking the package installation. You can either select the option (during installation) to only compile Apex in the package, or try to fix the errors in your Apex class.

**Comment by ShijiMathew** [comment]
Thankyou for your quick response @jongpie. Installation worked with compilation of apex in the package. This is a new class working by my colleague so I was not aware of it. I will close this issue.
